Configurations:
#  AssignmentNullUnionOperator
  - FindTemplate: |-
      if ($var$ $sign$ null)
      {
          $var$ = $value$;
      }
    FindRules:
      - $sign$ In ("is", "==", "!=", "is not")
    ReplaceTemplate: |-
      $var$ ??= $value$;

#  NullUnionOperator    

  - FindTemplate: |-
      if ($value$ $sign$ null)
          $var$ = $value2$;
      else
          $var$ = $value1$;
    FindRules:
      - $sign$ In ("is", "==", "!=", "is not")
    ReplaceTemplate: |-
      $var$ = $value1$ ?? $value2$;
    ReplaceRules:
      - $sign$ In ("!=", "is not") then $value2$ => $value1$, $value1$ => $value2$
      
#  TernaryOperator   
  
  - FindTemplate: |-
      if ($condition$)
          return $value1$;
      else
          return $value2$;
    ReplaceTemplate: |-
        return $condition$? $value1$ : $value2$;